### ISSUE TITLE
Manual actions has AWS Internal userAgent field

### ISSUE THREAD

**Issue by okgolove** [cloudandthings/terraform-aws-clickops-notifier#24]
If I create an EC2 Instance using web console I see `userAgent: "AWS Internal"` in cloudtrail events. As a result this is not parsed as user action in web console. Is this an expected behaviour?

ref: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html
UserAgent part

**Comment by phzietsman** [comment]
This is a bit of a headache, AWS is starting to replace userAgent for console actions with `AWS Internal`. We will need to include it in our check for console actions, but this will result in a few false positives. This changed last year sometime (https://web.archive.org/web/20211006122310/https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html)

Thanks for raising this, we'll start looking into a solution.

**Comment by okgolove** [comment]
Isn't `sessionCredentialFromConsole` variable says a request came from webconsole? In case of it is then everything becomes even easier.

**Comment by phzietsman** [comment]
thanks for that, I'm going to implement that.

**Comment by phzietsman** [comment]
This has been fixed in v1.3.0, thanks for the feedback!
