### ISSUE TITLE
Allow user provided IAM role

### ISSUE THREAD

**Issue by sbrinkerhoff** [cloudandthings/terraform-aws-clickops-notifier#31]
# Summary

I work within an organization that restricts the creation of IAM roles in AWS.  While we _can_ create them with Terraform, it is not with `aws_iam_role`.  Many modules are supporting a passed IAM role ([reference](https://github.com/aws-ia/terraform-aws-eks-blueprints#input_create_iam_role)) that allows us to use the modules directly but provide our own IAM role.

Could you consider an optional user-provided IAM role for this Terraform?

**Comment by phzietsman** [comment]
That's a great suggestion, we'll add it in.
