### ISSUE TITLE
Allow specifying the amount of memory for lambda function

### ISSUE THREAD

**Issue by Rychard** [cloudandthings/terraform-aws-clickops-notifier#35]
With only 128MB of memory allocated to the lambda, some invocations are failing.  This seems to be a problem for accounts that generate large amounts of events, as the error is being thrown on the [line where the gzipped log files are being read](https://github.com/cloudandthings/terraform-aws-clickops-notifier/blob/main/lambda/app/main.py#L121). (Well, when it tries to parse the _contents_ of the log files as JSON, but you know what I mean)

```text
[ERROR] MemoryError
Traceback (most recent call last):
  File "/var/task/main.py", line 146, in handler
    raise e
  File "/var/task/main.py", line 121, in handler
    event_json = json.load(fh)
  File "/var/lang/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/var/lang/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
```

**Comment by phzietsman** [comment]
Thanks for the feedback! There is an open PR for this: https://github.com/cloudandthings/terraform-aws-clickops-notifier/pull/34.
