### ISSUE TITLE
Support for encrypted AWS Control Tower trails/logs

### ISSUE THREAD

**Issue by switchdk** [cloudandthings/terraform-aws-clickops-notifier#6]
Hi,

Thanks for making this Terraform module. It is just what we have been looking for, and we will be watching the development of it :pray: :clap: 

We have deployed it in our AWS Organizations created by AWS Control Tower but we are using Control Tower KMS encryption as announced by AWS [here](https://aws.amazon.com/about-aws/whats-new/2021/07/aws-control-tower-provides-support-kms-encryption/). The encryption uses a KMS key stored in the AWS Organizations Management account, which the ClickOps-Notifier Lambda function will need `decrypt` permissions to. How to configure cross-account KMS access is described by AWS [here](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying-external-accounts.html). I am aware the module will only be able to make changes to the `Log Archive` account (at least how we manage AWS accounts) but it would be fantastic to include an option to create the IAM policy statement to use a management account KMS key.

Many thanks for your work.

**Comment by phzietsman** [comment]
Addressed in: https://github.com/cloudandthings/terraform-aws-clickops-notifier/pull/10
