### ISSUE TITLE
AccessDenied to `lambda:GetLayerVersion`

### ISSUE THREAD

**Issue by switchdk** [cloudandthings/terraform-aws-clickops-notifier#9]
Hi,

I just tried to deploy release 1.0.7 (thank you for the update) but I run into a permissions issue, I have not encountered before. 

When running Terraform (version 1.1.7), I get the following error

```
module.clickops_notifier.aws_lambda_function.func: Creating...
╷
│ Error: error creating Lambda Function (1): AccessDeniedException: 
│ 	status code: 403, request id: 3d590222-7f98-456f-b4fe-2f4014404436
│ 
│   with module.clickops_notifier.aws_lambda_function.func,
│   on .terraform/modules/clickops_notifier/lambda.tf line 1, in resource "aws_lambda_function" "func":
│    1: resource "aws_lambda_function" "func" {
```

When checking Cloudtrail for the AWS account in question, I see the following `AccessDenied` message.

```
"errorCode": "AccessDenied",
"errorMessage": "User: arn:aws:sts::ZZZZZZZZZ:assumed-role/AWSReservedSSO_AWSAdministratorAccess_zzzzzzzzzz/zzz@zzz.com is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-central-1:306986787463:layer:common-python-libraries:1 because no resource-based policy allows the lambda:GetLayerVersion action"
```

Could this relate to the recent release with updated layers? Would it be possible to make the layers public, if they aren't already? 

Thanks,

**Comment by phzietsman** [comment]
Shoot, it could be that some layers were not made public with the GH action. I've made this one public, I'll need to add a check to check that all layers are public.

Sorry about that.

For reference here is the repo with the layers (https://github.com/phzietsman/aws-lambda-layer-common)

**Comment by switchdk** [comment]
no worries @phzietsman I ran Terraform again and it works for us now (for eu-central-1). Have not tried any other regions.

**Comment by phzietsman** [comment]
I ran this and found a few that were not public.

```bash
for region in us-east-2 us-east-1 us-west-1 us-west-2 af-south-1 ap-east-1 ap-southeast-3 ap-south-1 ap-northeast-3 ap-northeast-2 ap-southeast-1 ap-southeast-2 ap-northeast-1 ca-central-1 eu-central-1 eu-west-1 eu-west-2 eu-south-1 eu-west-3 eu-north-1 me-south-1 sa-east-1
do
    aws lambda add-layer-version-permission \
    --region $region \
    --layer-name "common-python-libraries" \
    --statement-id public \
    --action lambda:GetLayerVersion  \
    --principal "*" \
    --version-number 1
done
```
